name = "MaxiCP"
uuid = "dd54a895-6957-4fd6-baf5-19ebd33a667e"
version = "0.1.0"
authors = ["Beno√Æt Legat <benoit.legat@gmail.com>"]

[deps]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
JavaCall = "494afd89-becb-516b-aafa-70d2670c0337"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
JavaCall = "0.8"
Test = "1.11.0"
julia = "1.6"
