name = "MaxiCP"
uuid = "dd54a895-6957-4fd6-baf5-19ebd33a667e"
version = "0.1.0"
authors = ["Beno√Æt Legat <benoit.legat@gmail.com>"]

[deps]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
JavaCall = "494afd89-becb-516b-aafa-70d2670c0337"

[compat]
Downloads = "1"
JavaCall = "0.8"
julia = "1.10"
